### ISSUE TITLE
Docker image manifest

### ISSUE THREAD

**Issue by giteki** [Benoit3/Diematic_to_MQTT#12]
Bonjour Benoit,

It seems there is a problem with the docker manifest when trying to retrieve images from ghcr.io (on aarch64 plateform / pi4)

$ docker -v
Docker version 20.10.5+dfsg1, build 55c4c88

$ docker pull  ghcr.io/benoit3/diematic_to_mqtt:latest
latest: Pulling from benoit3/diematic_to_mqtt
manifest unknown

$ uname -a
Linux xxxx 6.1.47-v8+ #1674 SMP PREEMPT Fri Aug 25 13:17:22 BST 2023 aarch64 GNU/Linux

**Comment by Benoit3** [comment]
Hello,

I thank you for your feedback.
I didn't understand what's happen because it was testes OK 6 months ago with an PC/Ubuntu 20.04 x86_64 GNU/Linux PC ( platform info given by docker version is " linux/amd64" ) and with a Rpi/ Bullseye aarch64 GNU/Linux ( platform info given by docker version is " linux/arm64" ). Same tests are now KO.

As I didn't modify the repository, solution is not obvious. It may take some days to find it (an access pb to manifests? An expired certificate somewhere?, docker pull  command is not verbose :-( ). If you need a result quickly I can suggest you [manual installation ](https://github.com/Benoit3/Diematic_to_MQTT/wiki/Raspbian-Installation)
Regards,
Benoit

**Comment by Benoit3** [comment]
Id did a near dummy update to force image rebuild.
Seems to work....
I didn't understand really what's happen...
Can you confirm ??

**Comment by giteki** [comment]
Everything is ok now after your rebuild.
I confirm that I can download the docker image without any troubles. I've no idea about the reason why it was broken, but this issue is now solved.
Thanks Benoit.
